// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHtyqup-DTgqcIWMjN_vu_U2xooXU7YS8',
    appId: '1:280824827829:web:76a65a950e27238cb653fc',
    messagingSenderId: '280824827829',
    projectId: 'countmein-gp1',
    authDomain: 'countmein-gp1.firebaseapp.com',
    storageBucket: 'countmein-gp1.appspot.com',
    measurementId: 'G-FTL7BG3PH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0thcgJvcjKo2a4bfTna7IywotlyQYiIs',
    appId: '1:280824827829:android:1ecf606e7cdeed60b653fc',
    messagingSenderId: '280824827829',
    projectId: 'countmein-gp1',
    storageBucket: 'countmein-gp1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMZm9CEx-mpFP0Jocj_bMGDoP9PoWAbDU',
    appId: '1:280824827829:ios:24f942b71f6f1888b653fc',
    messagingSenderId: '280824827829',
    projectId: 'countmein-gp1',
    storageBucket: 'countmein-gp1.appspot.com',
    iosClientId: '280824827829-s3tn6m41p6pr1pl1aqpsn0k5qu64p265.apps.googleusercontent.com',
    iosBundleId: 'com.example.main',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMZm9CEx-mpFP0Jocj_bMGDoP9PoWAbDU',
    appId: '1:280824827829:ios:24f942b71f6f1888b653fc',
    messagingSenderId: '280824827829',
    projectId: 'countmein-gp1',
    storageBucket: 'countmein-gp1.appspot.com',
    iosClientId: '280824827829-s3tn6m41p6pr1pl1aqpsn0k5qu64p265.apps.googleusercontent.com',
    iosBundleId: 'com.example.main',
  );
}
